In [ ]:
import pandas as pd
import numpy as np

ds = pd.Series([10,20,30],index=['D','E','V'],dtype='float',name='dev')
print(ds)

In [3]:
import pandas as pd
import numpy as np

ds = pd.Series({"d":40,"e":100,"v":40},dtype='float',name='dev')
print(ds)

d     40.0
e    100.0
v     40.0
Name: dev, dtype: float64

In [2]:
import pandas as pd
import numpy as np

ds = pd.Series(np.array([10,20,30]),index=['D','E','V'],dtype='float',name='dev')
print(ds)

D    10.0
E    20.0
V    30.0
Name: dev, dtype: float64

In [9]:
ds = pd.DataFrame([['d','e','v'],[10,20,30],['h','e','t']],index=['a','b','c'],columns=['p','q','r'])
print(ds)

    p   q   r
a   d   e   v
b  10  20  30
c   h   e   t

In [13]:
ds = pd.DataFrame({'name':['dev','het','jay'],"marks":[10,20,30],'gpa':[7,7.5,6.5]})
print(ds)

  name  marks  gpa
0  dev     10  7.0
1  het     20  7.5
2  jay     30  6.5

In [45]:
df= pd.read_csv('train.csv')
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [40]:
df.index
df.columns
df.size
df.shape
df.values
df.dtypes
df.ndim
df.T  #transpose
df = df.set_index('Name')

In [43]:
df = df.reset_index()

In [46]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [51]:
ds1 = pd.DataFrame({'name':['dev','het','jay'],"marks":[10,20,30],'CGPI':[7,7.5,6.5]},index=['V','H','A'])
print(ds1)

  name  marks  CGPI
V  dev     10   7.0
H  het     20   7.5
A  jay     30   6.5

In [57]:
ds1.set_index('name',drop=True)

In [54]:
ds1.set_index('name',drop=False)

     name  marks  CGPI
name
dev   dev     10   7.0
het   het     20   7.5
jay   jay     30   6.5

In [60]:
print(ds1)

  name  marks  CGPI
0  dev     10   7.0
1  het     20   7.5
2  jay     30   6.5

In [59]:
ds1 = ds1.reset_index()

In [61]:
df = pd.read_csv('train.csv')
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [72]:
df[['Name',"Age"]]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

In [66]:
type(df['Name'])

pandas.core.frame.DataFrame

In [81]:
df.iloc[2,3] #particular position
df.iloc[2] #3rd row

PassengerId                         3
Survived                            1
Pclass                              3
Name           Heikkinen, Miss. Laina
Sex                            female
Age                                26
SibSp                               0
Parch                               0
Ticket               STON/O2. 3101282
Fare                            7.925
Cabin                             NaN
Embarked                            S
Name: 2, dtype: object

In [74]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [82]:
df.iloc[1:10,2:5]

   Pclass                                               Name     Sex
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2       3                             Heikkinen, Miss. Laina  female
3       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
4       3                           Allen, Mr. William Henry    male
5       3                                   Moran, Mr. James    male
6       1                            McCarthy, Mr. Timothy J    male
7       3                     Palsson, Master. Gosta Leonard    male
8       3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female
9       2                Nasser, Mrs. Nicholas (Adele Achem)  female

In [89]:
df =df.set_index('Name')

In [90]:
df.index

Index(['Braund, Mr. Owen Harris',
       'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
       'Heikkinen, Miss. Laina',
       'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
       'Allen, Mr. William Henry', 'Moran, Mr. James',
       'McCarthy, Mr. Timothy J', 'Palsson, Master. Gosta Leonard',
       'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
       'Nasser, Mrs. Nicholas (Adele Achem)',
       ...
       'Markun, Mr. Johann', 'Dahlberg, Miss. Gerda Ulrika',
       'Banfield, Mr. Frederick James', 'Sutehall, Mr. Henry Jr',
       'Rice, Mrs. William (Margaret Norton)', 'Montvila, Rev. Juozas',
       'Graham, Miss. Margaret Edith',
       'Johnston, Miss. Catherine Helen "Carrie"', 'Behr, Mr. Karl Howell',
       'Dooley, Mr. Patrick'],
      dtype='object', name='Name', length=891)

In [94]:
df.loc['Braund, Mr. Owen Harris']

PassengerId            1
Survived               0
Pclass                 3
Sex                 male
Age                   22
SibSp                  1
Parch                  0
Ticket         A/5 21171
Fare                7.25
Cabin                NaN
Embarked               S
Name: Braund, Mr. Owen Harris, dtype: object

In [95]:
df.loc['Braund, Mr. Owen Harris','PassengerId':'Age']

PassengerId       1
Survived          0
Pclass            3
Sex            male
Age              22
Name: Braund, Mr. Owen Harris, dtype: object

In [97]:
ds1 = pd.DataFrame([[10,20,30],[40,50,60],[70,80,90]],index=['a','b','c'],columns=['p','q','r'])
print(ds1)

    p   q   r
a  10  20  30
b  40  50  60
c  70  80  90

In [109]:
ds1.loc['b','q']=100

In [111]:
ds1.loc['b','q']

100

In [108]:
ds1.loc[:,'r']

a    30
b    60
c    90
Name: r, dtype: int64

In [112]:
ds1['D']=7

In [113]:
ds1

    p    q   r  D
a  10   20  30  7
b  40  100  60  7
c  70   80  90  7

In [115]:
ds1['D']=ds1['p']*ds1['q']

In [116]:
ds1

    p    q   r     D
a  10   20  30   200
b  40  100  60  4000
c  70   80  90  5600

In [117]:
ds1.loc['a':'c','p':'r']=7

In [118]:
ds1

   p  q  r     D
a  7  7  7   200
b  7  7  7  4000
c  7  7  7  5600