In [41]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randint(1,100,(10,4)),columns=['a','b','c','d'])

In [42]:
df

    a   b   c   d
0  84  24  16  20
1  54   8  10  97
2   5  11  15  60
3  61  99  73  40
4  26  31   2  17
5   2  25  26  91
6  47  36  83  69
7   4  76  72  15
8   1  56  25  38
9  68  87  77  62

In [18]:
df.apply(sum,axis=1)

0    130
1    242
2    132
3    256
4    251
5    177
6    287
7    227
8    205
9    210
dtype: int64

In [19]:
df.apply(lambda x:(x['a']+x['b']+x['c'])/3,axis=1)

0    40.333333
1    75.333333
2    42.666667
3    52.666667
4    51.000000
5    35.666667
6    75.000000
7    62.000000
8    50.666667
9    48.000000
dtype: float64

In [20]:
df.apply(lambda x:'Fail' if ((x["a"]<35)or(x["b"]<35)or(x["c"]<35)or(x["d"]<35)) else 'Pass',axis=1)

0    Fail
1    Fail
2    Fail
3    Pass
4    Fail
5    Fail
6    Pass
7    Fail
8    Pass
9    Fail
dtype: object

In [13]:
df

    a   b   c   d
0  30  16  13  24
1  76  63  31   4
2  39  92  57  42
3   7  28  53   6
4  97  49  98  49
5  60  41  87  41
6  59  44  25  13
7  73  24  35  42
8  32  19  34  18
9  10   5  10  84

In [25]:
def Grade(Total):
    if Total>200:
        return "A+"
    if Total>200:
        return "A"
    if Total>200:
        return "B"
    if Total>200:
        return "C"
    return "F"

In [33]:
df["Grade"]=df["Total"].apply(Grade)

In [31]:
df["Total"]=df.apply(sum,axis=1)

In [34]:
df

    a   b   c   d  Total Grade
0  91  72  74  70    307    A+
1  70  77  10  41    198     F
2  41  72  80  98    291    A+
3  30  58  77  58    223    A+
4  24  37   9   4     74     F
5  73  49   6  34    162     F
6  94  54  44  38    230    A+
7  78  67  18  59    222    A+
8  74  69  15  98    256    A+
9  53  54  62  39    208    A+

In [44]:
df[['r','x']]=df.apply([sum,max],axis=1,result_type='expand')

In [45]:
df

    a   b   c   d    r   x
0  84  24  16  20  144  84
1  54   8  10  97  169  97
2   5  11  15  60   91  60
3  61  99  73  40  273  99
4  26  31   2  17   76  31
5   2  25  26  91  144  91
6  47  36  83  69  235  83
7   4  76  72  15  167  76
8   1  56  25  38  120  56
9  68  87  77  62  294  87